baseURL = "https://foreachx.github.io/justinas.github.io"
languageCode = "en-us"
title = "Justinas Vijeikis ITnt-24"
theme = "ananke"
relativeURLs = false
publishDir = "docs"
canonifyURLs = true
[menu]
  [[menu.main]]
    identifier = "apie"
    name = "Apie"
    url = "/apie/"
    weight = 2
