baseURL = "https://foreachx.github.io/"
languageCode = "en-us"
title = "Justinas Vijeikis ITnt-24"
theme = "ananke"
[menu]
  [[menu.main]]
    identifier = "apie"
    name = "Apie"
    url = "/apie/"
    weight = 2
